const data = {
  products: [
    {
      id: 8853,
      name: "HP Notebook 15/BL1K4EA ",
      price: 1749.99,
      previousPrice: null,
      barCode: "I99910",
      imageUrl:
        "https://static.ee.ge/Elite/bda2e882-8fcb-43d8-b6b5-3788f98cfcfa_Thumb.png",
      orderNo: -2,
      hasDiscount: false,
      isFavorite: false,
      isInCart: false,
      route: "noutbuqebi/hp-notebook-15-bl1k4ea-p8853",
      onSaleSoon: false,
      storageQuantity: 106,
      requestedQuantity: 0,
      disableBuyButton: false,
      doNotRecordStock: false,
      isPreOrderProduct: false,
      preOrderPartialPrice: null,
      preOrderDescription: null,
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      brandName: "HP",
      promotionAvailableQuantity: null,
      promotionSoldQuantity: null,
      discountAmount: 0,
      discountPercent: 0,
      labelColor: null,
      labelText: null,
      iconUrl: null,
      gifts: null,
      giftType: null,
    },
    {
      id: 7440,
      name: 'Apple MacBook Air 13" M1 chip 256GB Space Grey MGN63RU',
      price: 2149.99,
      previousPrice: null,
      barCode: "I74162",
      imageUrl:
        "https://static.ee.ge/Elite/dff1eb34-ba6f-4942-8430-5e85bc1ace74_Thumb.jpeg",
      orderNo: -1,
      hasDiscount: false,
      isFavorite: false,
      isInCart: false,
      route:
        "noutbuqebi/apple-macbook-air-13-m1-chip-256gb-space-grey-mgn63ru-p7440",
      onSaleSoon: false,
      storageQuantity: 33,
      requestedQuantity: 0,
      disableBuyButton: false,
      doNotRecordStock: false,
      isPreOrderProduct: false,
      preOrderPartialPrice: null,
      preOrderDescription: null,
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      brandName: "APPLE",
      promotionAvailableQuantity: null,
      promotionSoldQuantity: null,
      discountAmount: 0,
      discountPercent: 0,
      labelColor: null,
      labelText: null,
      iconUrl: null,
      gifts: null,
      giftType: null,
    },
    {
      id: 9146,
      name: "ASUS Vivobook 15/X1504VA-BQ151 Silver",
      price: 1199.99,
      previousPrice: 1399.99,
      barCode: "I100134",
      imageUrl:
        "https://static.ee.ge/Elite/6261a149-4e75-4384-950b-f7dfff4a4662_Thumb.png",
      orderNo: 0,
      hasDiscount: false,
      isFavorite: false,
      isInCart: false,
      route: "noutbuqebi/asus-vivobook-15-x1504va-bq151-silver-p9146",
      onSaleSoon: false,
      storageQuantity: 17,
      requestedQuantity: 0,
      disableBuyButton: false,
      doNotRecordStock: false,
      isPreOrderProduct: false,
      preOrderPartialPrice: null,
      preOrderDescription: null,
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      brandName: "ASUS",
      promotionAvailableQuantity: null,
      promotionSoldQuantity: null,
      discountAmount: 0,
      discountPercent: 0,
      labelColor: null,
      labelText: null,
      iconUrl: null,
      gifts: null,
      giftType: null,
    },
    {
      id: 9147,
      name: "ASUS Vivobook 15/X1504VA-BQ008 Silver",
      price: 1099.99,
      previousPrice: 1249.99,
      barCode: "I100135",
      imageUrl:
        "https://static.ee.ge/Elite/a4aabfec-2fb6-47cb-90c9-33c1f2df3e7f_Thumb.png",
      orderNo: 0,
      hasDiscount: false,
      isFavorite: false,
      isInCart: false,
      route: "noutbuqebi/asus-vivobook-15-x1504va-bq008-silver-p9147",
      onSaleSoon: false,
      storageQuantity: 18,
      requestedQuantity: 0,
      disableBuyButton: false,
      doNotRecordStock: false,
      isPreOrderProduct: false,
      preOrderPartialPrice: null,
      preOrderDescription: null,
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      brandName: "ASUS",
      promotionAvailableQuantity: null,
      promotionSoldQuantity: null,
      discountAmount: 0,
      discountPercent: 0,
      labelColor: null,
      labelText: null,
      iconUrl: null,
      gifts: null,
      giftType: null,
    },
    {
      id: 9148,
      name: "ASUS Vivobook 15/M1502YA-BQ606 Blue",
      price: 1499.99,
      previousPrice: 1699.99,
      barCode: "I100136",
      imageUrl:
        "https://static.ee.ge/Elite/6a1e9ba0-52e5-4e76-b757-ff8fe8a5dc62_Thumb.png",
      orderNo: 0,
      hasDiscount: false,
      isFavorite: false,
      isInCart: false,
      route: "noutbuqebi/asus-vivobook-15-m1502ya-bq606-blue-p9148",
      onSaleSoon: false,
      storageQuantity: 17,
      requestedQuantity: 0,
      disableBuyButton: false,
      doNotRecordStock: false,
      isPreOrderProduct: false,
      preOrderPartialPrice: null,
      preOrderDescription: null,
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      brandName: "ASUS",
      promotionAvailableQuantity: null,
      promotionSoldQuantity: null,
      discountAmount: 0,
      discountPercent: 0,
      labelColor: null,
      labelText: null,
      iconUrl: null,
      gifts: null,
      giftType: null,
    },
    {
      id: 9149,
      name: "ASUS Vivobook 15/X1504VA-BQ3123 Blue",
      price: 1599.99,
      previousPrice: 1799.99,
      barCode: "I100137",
      imageUrl:
        "https://static.ee.ge/Elite/384ebc03-e7c9-4eda-a624-10446206a86b_Thumb.jpeg",
      orderNo: 0,
      hasDiscount: false,
      isFavorite: false,
      isInCart: false,
      route: "noutbuqebi/asus-vivobook-15-x1504va-bq3123-blue-p9149",
      onSaleSoon: false,
      storageQuantity: 17,
      requestedQuantity: 0,
      disableBuyButton: false,
      doNotRecordStock: false,
      isPreOrderProduct: false,
      preOrderPartialPrice: null,
      preOrderDescription: null,
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      brandName: "ASUS",
      promotionAvailableQuantity: null,
      promotionSoldQuantity: null,
      discountAmount: 0,
      discountPercent: 0,
      labelColor: null,
      labelText: null,
      iconUrl: null,
      gifts: null,
      giftType: null,
    },
    {
      id: 9150,
      name: "ASUS Vivobook 15 OLED/X1505VA-L1595",
      price: 1649.99,
      previousPrice: 1899.99,
      barCode: "I100138",
      imageUrl:
        "https://static.ee.ge/Elite/d5928058-4f44-43ab-ae87-ff8859b1915a_Thumb.png",
      orderNo: 0,
      hasDiscount: false,
      isFavorite: false,
      isInCart: false,
      route: "noutbuqebi/asus-vivobook-15-oled-x1505va-l1595-p9150",
      onSaleSoon: false,
      storageQuantity: 5,
      requestedQuantity: 0,
      disableBuyButton: false,
      doNotRecordStock: false,
      isPreOrderProduct: false,
      preOrderPartialPrice: null,
      preOrderDescription: null,
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      brandName: "ASUS",
      promotionAvailableQuantity: null,
      promotionSoldQuantity: null,
      discountAmount: 0,
      discountPercent: 0,
      labelColor: null,
      labelText: null,
      iconUrl: null,
      gifts: null,
      giftType: null,
    },
    {
      id: 9167,
      name: "ASUS Vivobook Go 15//E1504FA-BQ521 Green",
      price: 1499.99,
      previousPrice: 1699.99,
      barCode: "I100139",
      imageUrl:
        "https://static.ee.ge/Elite/b6aeb1e9-4f1b-453f-91a3-fa27ddccb573_Thumb.jpeg",
      orderNo: 0,
      hasDiscount: false,
      isFavorite: false,
      isInCart: false,
      route: "noutbuqebi/asus-vivobook-go-15-e1504fa-bq521-green-p9167",
      onSaleSoon: false,
      storageQuantity: 8,
      requestedQuantity: 0,
      disableBuyButton: false,
      doNotRecordStock: false,
      isPreOrderProduct: false,
      preOrderPartialPrice: null,
      preOrderDescription: null,
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      brandName: "ASUS",
      promotionAvailableQuantity: null,
      promotionSoldQuantity: null,
      discountAmount: 0,
      discountPercent: 0,
      labelColor: null,
      labelText: null,
      iconUrl: null,
      gifts: null,
      giftType: null,
    },
    {
      id: 9171,
      name: "HP Notebook Pavilion Clamshell/B4LY9EA",
      price: 2049.99,
      previousPrice: null,
      barCode: "I97490",
      imageUrl:
        "https://static.ee.ge/Elite/30b51157-b13a-4502-a1d2-c4a53db11774_Thumb.jpeg",
      orderNo: 0,
      hasDiscount: false,
      isFavorite: false,
      isInCart: false,
      route: "noutbuqebi/hp-notebook-pavilion-clamshell-b4ly9ea-p9171",
      onSaleSoon: false,
      storageQuantity: 8,
      requestedQuantity: 0,
      disableBuyButton: false,
      doNotRecordStock: false,
      isPreOrderProduct: false,
      preOrderPartialPrice: null,
      preOrderDescription: null,
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      brandName: "HP",
      promotionAvailableQuantity: null,
      promotionSoldQuantity: null,
      discountAmount: 0,
      discountPercent: 0,
      labelColor: null,
      labelText: null,
      iconUrl: null,
      gifts: null,
      giftType: null,
    },
    {
      id: 9172,
      name: "HP Notebook EliteBook 660 G11/9C075EA",
      price: 2399.99,
      previousPrice: null,
      barCode: "I98128",
      imageUrl:
        "https://static.ee.ge/Elite/56b0e6f9-dd27-4ab2-91c2-0eb3c0d2ec94_Thumb.png",
      orderNo: 0,
      hasDiscount: false,
      isFavorite: false,
      isInCart: false,
      route: "noutbuqebi/hp-notebook-elitebook-660-g11-9c075ea-p9172",
      onSaleSoon: false,
      storageQuantity: 7,
      requestedQuantity: 0,
      disableBuyButton: false,
      doNotRecordStock: false,
      isPreOrderProduct: false,
      preOrderPartialPrice: null,
      preOrderDescription: null,
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      brandName: "HP",
      promotionAvailableQuantity: null,
      promotionSoldQuantity: null,
      discountAmount: 0,
      discountPercent: 0,
      labelColor: null,
      labelText: null,
      iconUrl: null,
      gifts: null,
      giftType: null,
    },
    {
      id: 6636,
      name: "Acer Aspire Lite 16 (NX.J5SER.001)",
      price: 1479.99,
      previousPrice: null,
      barCode: "I97239",
      imageUrl:
        "https://static.ee.ge/Elite/22c8c137-7065-45ef-80db-a4e3c5b03a87_Thumb.jpeg",
      orderNo: 1,
      hasDiscount: false,
      isFavorite: false,
      isInCart: false,
      route: "noutbuqebi/acer-aspire-lite-16-nx-j5ser-001-p6636",
      onSaleSoon: false,
      storageQuantity: 24,
      requestedQuantity: 0,
      disableBuyButton: false,
      doNotRecordStock: false,
      isPreOrderProduct: false,
      preOrderPartialPrice: null,
      preOrderDescription: null,
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      brandName: "ACER",
      promotionAvailableQuantity: null,
      promotionSoldQuantity: null,
      discountAmount: 0,
      discountPercent: 0,
      labelColor: null,
      labelText: null,
      iconUrl: null,
      gifts: null,
      giftType: null,
    },
    {
      id: 8021,
      name: "HUAWEI MateBook D 16/53014CNB Space Gray",
      price: 1399.99,
      previousPrice: 1649.99,
      barCode: "I99038",
      imageUrl:
        "https://static.ee.ge/Elite/6e3ab4ba-885c-4306-9103-ccd2934dc687_Thumb.jpeg",
      orderNo: 2,
      hasDiscount: false,
      isFavorite: false,
      isInCart: false,
      route: "noutbuqebi/huawei-matebook-d-16-53014cnb-space-gray-p8021",
      onSaleSoon: false,
      storageQuantity: 27,
      requestedQuantity: 0,
      disableBuyButton: false,
      doNotRecordStock: false,
      isPreOrderProduct: false,
      preOrderPartialPrice: null,
      preOrderDescription: null,
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      brandName: "HUAWEI",
      promotionAvailableQuantity: null,
      promotionSoldQuantity: null,
      discountAmount: 0,
      discountPercent: 0,
      labelColor: null,
      labelText: null,
      iconUrl: null,
      gifts: null,
      giftType: null,
    },
    {
      id: 7138,
      name: "Dell Vostro 3530/N3404PVNB3530EMEA01_UBU_GE",
      price: 1499.99,
      previousPrice: 1899.99,
      barCode: "I98019",
      imageUrl:
        "https://static.ee.ge/Elite/9b94ad4c-a4aa-4c6e-a3ee-847db1e08f5d_Thumb.png",
      orderNo: 3,
      hasDiscount: false,
      isFavorite: false,
      isInCart: false,
      route: "noutbuqebi/dell-vostro-3530-n3404pvnb3530emea01-ubu-ge-p7138",
      onSaleSoon: false,
      storageQuantity: 20,
      requestedQuantity: 0,
      disableBuyButton: false,
      doNotRecordStock: false,
      isPreOrderProduct: false,
      preOrderPartialPrice: null,
      preOrderDescription: null,
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      brandName: "DELL",
      promotionAvailableQuantity: null,
      promotionSoldQuantity: null,
      discountAmount: 0,
      discountPercent: 0,
      labelColor: null,
      labelText: null,
      iconUrl: null,
      gifts: null,
      giftType: null,
    },
    {
      id: 7169,
      name: "Dell Vostro 3530/N1612QVNB3530EMEA01_UBU_GE",
      price: 1199.99,
      previousPrice: 1699.99,
      barCode: "I98018",
      imageUrl:
        "https://static.ee.ge/Elite/dacc2253-7710-4605-bf94-345318fa2a26_Thumb.png",
      orderNo: 4,
      hasDiscount: false,
      isFavorite: false,
      isInCart: false,
      route: "noutbuqebi/dell-vostro-3530-n1612qvnb3530emea01-ubu-ge-p7169",
      onSaleSoon: false,
      storageQuantity: 19,
      requestedQuantity: 0,
      disableBuyButton: false,
      doNotRecordStock: false,
      isPreOrderProduct: false,
      preOrderPartialPrice: null,
      preOrderDescription: null,
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      brandName: "DELL",
      promotionAvailableQuantity: null,
      promotionSoldQuantity: null,
      discountAmount: 0,
      discountPercent: 0,
      labelColor: null,
      labelText: null,
      iconUrl: null,
      gifts: null,
      giftType: null,
    },
    {
      id: 8022,
      name: "HUAWEI MateBook D 16/53014BUY Space Gray",
      price: 1699.99,
      previousPrice: 1899.99,
      barCode: "I99039",
      imageUrl:
        "https://static.ee.ge/Elite/8b59d662-cade-407b-a7e2-f3bcefebf5cf_Thumb.jpeg",
      orderNo: 5,
      hasDiscount: false,
      isFavorite: false,
      isInCart: false,
      route: "noutbuqebi/huawei-matebook-d-16-53014buy-space-gray-p8022",
      onSaleSoon: false,
      storageQuantity: 18,
      requestedQuantity: 0,
      disableBuyButton: false,
      doNotRecordStock: false,
      isPreOrderProduct: false,
      preOrderPartialPrice: null,
      preOrderDescription: null,
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      brandName: "HUAWEI",
      promotionAvailableQuantity: null,
      promotionSoldQuantity: null,
      discountAmount: 0,
      discountPercent: 0,
      labelColor: null,
      labelText: null,
      iconUrl: null,
      gifts: null,
      giftType: null,
    },
    {
      id: 4820,
      name: "Acer Aspire 3 (NX.KDEER.00E) Black",
      price: 1229.99,
      previousPrice: 1449.99,
      barCode: "I93419",
      imageUrl:
        "https://static.ee.ge/Elite/be43b0f7-7e3d-4dba-9810-aeb26a8ca1d0_Thumb.jpeg",
      orderNo: 6,
      hasDiscount: false,
      isFavorite: false,
      isInCart: false,
      route: "noutbuqebi/acer-aspire-3-nx-kdeer-00e-black-p4820",
      onSaleSoon: false,
      storageQuantity: 14,
      requestedQuantity: 0,
      disableBuyButton: false,
      doNotRecordStock: false,
      isPreOrderProduct: false,
      preOrderPartialPrice: null,
      preOrderDescription: null,
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      brandName: "ACER",
      promotionAvailableQuantity: null,
      promotionSoldQuantity: null,
      discountAmount: 0,
      discountPercent: 0,
      labelColor: null,
      labelText: null,
      iconUrl: null,
      gifts: null,
      giftType: null,
    },
  ],
  categories: [
    {
      categoryId: 58,
      categoryName: "ნოუთბუქები",
      parentCategoryId: 27,
      parentCategoryName: "კომპიუტერები და გეიმინგი",
      orderNo: 0,
    },
  ],
  popularSearches: [
    "ქეშბექ აქცია",
    "აუთლეტი",
    "iPhone Air",
    "iPhone 17",
    "ონლაინ აქცია",
    "ცივი ყავის აპარატი",
    "უსადენო მტვერსასრუტი საჩუქრად",
    "კონდიციონერი",
    "გამათბობელი",
    "Z Fold 7",
    "ხელის მტვერსასრუტი",
    "რობოტი მტვერსასრუტი",
    "სმარტ საათი",
    "SONY XM6",
    "Dreame",
    "სკუტერი",
    "Airpods",
    "SIGMA",
    "iPhone 16 pro",
    "LG Moodup",
    "Galaxy s22",
    "აერო გრილი",
    "delonghi",
    "Bosch KGN56",
    "ninja",
    "airpods",
    "სავარძელი",
    "dyson",
    "a56",
    "SIGMA X-style 353 Black",
  ],
  productsCount: 224,
  categoryName: "კომპიუტერები და გეიმინგი-ნოუთბუქები",
  parentCategoryName: null,
  metaTitle: null,
  metaDescription: null,
  h1: null,
  httpStatusCode: 200,
  userMessage: null,
  developerMessage: null,
  success: true,
  errors: [],
};
